### ISSUE TITLE
What a great example! I remember making this program back in the day from a book on fractals!

### ISSUE THREAD

**Issue by lilithebowman** [adamlwgriffiths/qbasic-fractal#1]
https://github.com/adamlwgriffiths/qbasic-fractal/blob/7cea87ffd667451a92bbc8bd7c3d7bc9a3e1fa0a/MANDELBR.BAS#L33

In this line, I know you're trying to illustrate what you're doing by showing the 2^2, but doing that calculation on bare metal, on an XT class system like I'm doing right now, is pretty slow. So I changed this out for a 4.

The Micro8088 is a great project for QBASIC fun like this!

**Comment by adamlwgriffiths** [comment]
Glad you found value in it.
My plan was just to mess around with fractals in different languages. Ironically, I only got this one done.
I only used it in the Windows QBasic runtime which you can still download and run via DOSBox.

If you want to do a PR I can merge that, otherwise I can just make the change directly.

Also I recommend playing around with the colour value.
Because of the time taken to render, I didn't spend too much time tweaking it and settled for what is currently there.
Perhaps you can find better.
